apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stories
  template:
    metadata:
      labels:
        app: stories
    spec:
      containers:
        - name: stories
          image: kvitkovski/stories
      #     volumeMounts:
      #       - mountPath: /app/story
      #         name: story-volume
      #     ports:
      #       - containerPort: 3000
      # volumes:
      #   - name: story-volume
      #     persistentVolumeClaim:
      #       claimName: story-pvc
 